import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './components/Navbar/Navbar'
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css'
import {Knock} from '@knocklabs/node'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'SGP Cinema Admin',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) 
{
  // const knockClient = new Knock("sk_test_CxObjuVUM9OkqeH58OrwTcHl-15km9uxc6nouPtGJqM");
  // console.log(knockClient);
  
  // await knockClient.notify('movie',{
  //     actor: "123456",
  //     // recipients: otherUsers.map(user=>user.password),
  //     recipients:["123"],
  //     data : {
  //         workout: {
  //             value:  "ok"
  //         }
  //     }
  // });
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        <ToastContainer />
      </body>
    </html>
  )
}
